server:
  port: 8181
spring:
    jpa:
      hibernate:
        ddl-auto: update
# Settings for the oracle connection
    datasource:
        url:
            jdbc:oracle:thin:@localhost:1521:orcl
        username:
            system
        password:
            durga
        driver-class-oracle:
            jdbc:
                 driver

